module.exports = { url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1',
  labels_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1/labels{/name}',
  comments_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1/comments',
  events_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1/events',
  html_url: 'https://github.com/itsjoesullivan/tik/issues/1',
  id: 46571855,
  number: 1,
  title: 'test',
  user: 
   { login: 'itsjoesullivan',
     id: 964151,
     avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
     gravatar_id: '',
     url: 'https://api.github.com/users/itsjoesullivan',
     html_url: 'https://github.com/itsjoesullivan',
     followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
     following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
     gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
     organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
     repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
     events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
     received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
     type: 'User',
     site_admin: false },
  labels: 
   [ { url: 'https://api.github.com/repos/itsjoesullivan/tik/labels/asdf',
       name: 'asdf',
       color: 'ededed' },
     { url: 'https://api.github.com/repos/itsjoesullivan/tik/labels/awesome',
       name: 'awesome',
       color: '5319e7' } ],
  state: 'closed',
  locked: false,
  assignee: 
   { login: 'itsjoesullivan',
     id: 964151,
     avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
     gravatar_id: '',
     url: 'https://api.github.com/users/itsjoesullivan',
     html_url: 'https://github.com/itsjoesullivan',
     followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
     following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
     gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
     organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
     repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
     events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
     received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
     type: 'User',
     site_admin: false },
  milestone: null,
  comments: 21,
  created_at: '2014-10-22T23:12:27Z',
  updated_at: '2014-10-30T03:11:36Z',
  closed_at: '2014-10-30T02:39:51Z',
  body: 'This is a description of this ticket.',
  closed_by: 
   { login: 'itsjoesullivan',
     id: 964151,
     avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
     gravatar_id: '',
     url: 'https://api.github.com/users/itsjoesullivan',
     html_url: 'https://github.com/itsjoesullivan',
     followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
     following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
     gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
     organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
     repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
     events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
     received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
     type: 'User',
     site_admin: false } };
