module.exports = [ { url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/comments/60172751',
    html_url: 'https://github.com/itsjoesullivan/tik/issues/1#issuecomment-60172751',
    issue_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1',
    id: 60172751,
    user: 
     { login: 'itsjoesullivan',
       id: 964151,
       avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
       gravatar_id: '',
       url: 'https://api.github.com/users/itsjoesullivan',
       html_url: 'https://github.com/itsjoesullivan',
       followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
       following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
       gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
       organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
       repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
       events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
       received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
       type: 'User',
       site_admin: false },
    created_at: '2014-10-22T23:36:28Z',
    updated_at: '2014-10-22T23:36:28Z',
    body: 'A comment is left.' },
  { url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/comments/60182125',
    html_url: 'https://github.com/itsjoesullivan/tik/issues/1#issuecomment-60182125',
    issue_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1',
    id: 60182125,
    user: 
     { login: 'itsjoesullivan',
       id: 964151,
       avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
       gravatar_id: '',
       url: 'https://api.github.com/users/itsjoesullivan',
       html_url: 'https://github.com/itsjoesullivan',
       followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
       following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
       gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
       organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
       repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
       events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
       received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
       type: 'User',
       site_admin: false },
    created_at: '2014-10-23T01:45:49Z',
    updated_at: '2014-10-23T01:45:49Z',
    body: 'comment 2' },
  { url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/comments/60182329',
    html_url: 'https://github.com/itsjoesullivan/tik/issues/1#issuecomment-60182329',
    issue_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1',
    id: 60182329,
    user: 
     { login: 'itsjoesullivan',
       id: 964151,
       avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
       gravatar_id: '',
       url: 'https://api.github.com/users/itsjoesullivan',
       html_url: 'https://github.com/itsjoesullivan',
       followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
       following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
       gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
       organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
       repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
       events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
       received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
       type: 'User',
       site_admin: false },
    created_at: '2014-10-23T01:48:41Z',
    updated_at: '2014-10-23T01:48:41Z',
    body: 'this\r\nis a multi-line\r\n\r\ncomment' },
  { url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/comments/60182943',
    html_url: 'https://github.com/itsjoesullivan/tik/issues/1#issuecomment-60182943',
    issue_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1',
    id: 60182943,
    user: 
     { login: 'itsjoesullivan',
       id: 964151,
       avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
       gravatar_id: '',
       url: 'https://api.github.com/users/itsjoesullivan',
       html_url: 'https://github.com/itsjoesullivan',
       followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
       following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
       gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
       organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
       repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
       events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
       received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
       type: 'User',
       site_admin: false },
    created_at: '2014-10-23T01:59:32Z',
    updated_at: '2014-10-23T01:59:32Z',
    body: 'hello' },
  { url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/comments/60182983',
    html_url: 'https://github.com/itsjoesullivan/tik/issues/1#issuecomment-60182983',
    issue_url: 'https://api.github.com/repos/itsjoesullivan/tik/issues/1',
    id: 60182983,
    user: 
     { login: 'itsjoesullivan',
       id: 964151,
       avatar_url: 'https://avatars.githubusercontent.com/u/964151?v=2',
       gravatar_id: '',
       url: 'https://api.github.com/users/itsjoesullivan',
       html_url: 'https://github.com/itsjoesullivan',
       followers_url: 'https://api.github.com/users/itsjoesullivan/followers',
       following_url: 'https://api.github.com/users/itsjoesullivan/following{/other_user}',
       gists_url: 'https://api.github.com/users/itsjoesullivan/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/itsjoesullivan/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/itsjoesullivan/subscriptions',
       organizations_url: 'https://api.github.com/users/itsjoesullivan/orgs',
       repos_url: 'https://api.github.com/users/itsjoesullivan/repos',
       events_url: 'https://api.github.com/users/itsjoesullivan/events{/privacy}',
       received_events_url: 'https://api.github.com/users/itsjoesullivan/received_events',
       type: 'User',
       site_admin: false },
    created_at: '2014-10-23T02:00:16Z',
    updated_at: '2014-10-23T02:00:16Z',
    body: 'weee' }
];
